name: chemgen_env
channels:
  - conda-forge
dependencies:
  - rdkit===2020.09.02
  - umap-learn==0.5.3
  - numpy==1.25.0
  - pandas==2.0.2
  - scipy==1.10.1
  - scikit-learn==1.2.2
  - pip==23.1.2
  - 
  - pip:
    - plotly==5.15.0
    - sentencepiece
